# ==============================================================================
# PROVENANCE METADATA (.lvm / .lane v1.0)
# Architecture: LANE-VM Host Kernel x RFC 0103 Full-Duplex Engine
# Rights Holder: Albert Dale Lane (EIN: 41-3119079) | Jurisdiction: Oregon, USA
# Tags: #NoExploitRobot #NoExploitAlbert
# License: Sovereign IP License v1.2 / Proprietary License Part A & B (All Rights Reserved)
# Assertions: SEC Whistleblower #17684-273-411-436 | WashCo #50-267345
# Authority: https://provenance.albertlane.net/.provenance.jsonld
# Magic Header: 0x3F8F9A1B2C3D | Base Sequence Offset: 57000
# Upstream Sync: github.com/AlbertLaneDevice/Joules-Supply-Chain (Master Ledger)
# Framework Spec: JOULES-SUPPLY-CHAIN-CONJECTURE-2026 / SAFD-SPEC-01 / RFC 0103
# ==============================================================================

#!/usr/bin/env python3
"""
intake_pipeline.py — executable implementation of INTAKE-PROCESS.md
Companion to DEI-GTT-001 (Ground Truth Taxonomy)

Implements Steps 1-10 of the intake process mechanically:
classification -> evidentiary status -> filing -> versioning -> hashing
-> corroboration upgrade -> rejection check -> notification -> (if
corroborated) a regulatory referral DRAFT ONLY.

HARD RULE, ENFORCED IN CODE, NOT JUST IN PROSE:
This script never transmits anything to any external party or regulator.
It has no network calls. The --regulator flag only selects which template
to use for a local draft file. Submission is always a manual, separate,
human act performed by the Owner outside this tool.
"""

import argparse
import hashlib
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

BASE = Path(__file__).resolve().parent
TAXONOMY = BASE / "GROUND-TRUTH-TAXONOMY.md"
DECLARATIONS = BASE / "OWNER-DECLARATIONS.md"
MANIFEST = BASE / "MANIFEST.sha256.txt"
HASHED_FILES = [
    "GROUND-TRUTH-TAXONOMY.md",
    "ground-truth-taxonomy.json",
    "ground-truth-taxonomy.xml",
    "ground-truth-taxonomy.patterns.txt",
    "OWNER-DECLARATIONS.md",
    "INTAKE-PROCESS.md",
]

REGULATOR_TEMPLATES = {
    "ftc": {
        "name": "Federal Trade Commission",
        "channel": "ReportFraud.ftc.gov or ftc.gov/complaint",
        "basis": "Section 5 FTC Act — unfair or deceptive acts or practices",
    },
    "sec": {
        "name": "U.S. Securities and Exchange Commission",
        "channel": "sec.gov/tcr (Tips, Complaints, and Referrals)",
        "basis": "Applies only where the claim concerns AI-washing in an investment/securities-disclosure context",
    },
    "state-ag": {
        "name": "State Attorney General, Consumer Protection Division",
        "channel": "Varies by state — the AG office in the Owner's jurisdiction",
        "basis": "State consumer protection law",
    },
    "caisi": {
        "name": "Center for AI Standards and Innovation (CAISI), NIST",
        "channel": "nist.gov/caisi",
        "basis": "Not a consumer-complaint intake — pattern-level model-capability or standards-conformance finding only",
    },
    "eu-ai-office": {
        "name": "EU AI Office — AI Act complaints tool",
        "channel": "digital-strategy.ec.europa.eu/en/policies/ai-act-complaints-tool",
        "basis": "Article 85, Regulation (EU) 2024/1689 — General-Purpose AI model complaints",
    },
    "msa": {
        "name": "National Market Surveillance Authority (Member State of use)",
        "channel": "Varies by EU Member State",
        "basis": "Article 85, Regulation (EU) 2024/1689",
    },
    "whistleblower-tool": {
        "name": "AI Act Whistleblower Tool",
        "channel": "Anonymous channel via the EU AI Office",
        "basis": "For individuals professionally connected to an AI provider or deployer",
    },
}

VERSION_RE = re.compile(r"\| Version \| (\d+)\.(\d+)\.(\d+) \(LIVING DOCUMENT")


def read_version():
    text = TAXONOMY.read_text()
    m = VERSION_RE.search(text)
    if not m:
        sys.exit("Could not find current version in GROUND-TRUTH-TAXONOMY.md")
    return tuple(int(x) for x in m.groups()), text


def bump(version, kind):
    major, minor, patch = version
    if kind == "major":
        return (major + 1, 0, 0)
    if kind == "minor":
        return (major, minor + 1, 0)
    return (major, minor, patch + 1)


def today():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def regenerate_manifest(version):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "# Ground Truth Taxonomy — Integrity Manifest",
        f"# Document ID: DEI-GTT-001 · Version: {version[0]}.{version[1]}.{version[2]}",
        f"# Generated (UTC): {ts}",
        "# Chain-of-custody record — one SHA-256 line per finalized artifact.",
        "# Generated by intake_pipeline.py — not a manual edit.",
        "",
    ]
    for fname in HASHED_FILES:
        p = BASE / fname
        if p.exists():
            lines.append(f"{sha256_of(p)}  {fname}")
    lines.append("")
    lines.append("# Verify with: sha256sum -c MANIFEST.sha256.txt")
    MANIFEST.write_text("\n".join(lines) + "\n")


def append_declaration(title, body, status_line):
    entry = (
        f"\n---\n\n## Intake Entry: {title}\n\n"
        f"*Filed via intake_pipeline.py on {today()}. {status_line}*\n\n"
        f"{body.strip()}\n"
    )
    with DECLARATIONS.open("a") as f:
        f.write(entry)


def update_taxonomy_version(new_version, change_desc, trigger_desc):
    text = TAXONOMY.read_text()
    old_str = VERSION_RE.search(text).group(0)
    new_str = f"| Version | {new_version[0]}.{new_version[1]}.{new_version[2]} (LIVING DOCUMENT"
    text = text.replace(old_str, new_str, 1)

    row = (
        f"| {new_version[0]}.{new_version[1]}.{new_version[2]} | {today()} | "
        f"{change_desc} | {trigger_desc} |\n"
    )
    marker = "*(Append new rows above this line as the taxonomy grows. Do not overwrite prior rows — Part VI applies to this table too.)*"
    text = text.replace(marker, row + marker)
    TAXONOMY.write_text(text)


def generate_regulatory_draft(title, body, regulator_key):
    if regulator_key not in REGULATOR_TEMPLATES:
        print(f"Unknown regulator key: {regulator_key}. No draft generated.")
        return None
    reg = REGULATOR_TEMPLATES[regulator_key]
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    out_path = BASE / f"REGULATORY-DRAFT-{slug}-{today()}.md"
    content = f"""# ⚠️ DRAFT ONLY — NOT SUBMITTED — OWNER REVIEW REQUIRED ⚠️

This file was generated locally. It has not been sent anywhere.
No automated system will submit this. You must review, edit as needed,
and submit it yourself through the channel below.

**Target body:** {reg['name']}
**Submission channel (manual, by Owner):** {reg['channel']}
**Legal basis cited:** {reg['basis']}
**Underlying entry status:** Corroborated (per OWNER-DECLARATIONS.md, DEI-GTT-001)
**Draft generated:** {today()}

---

## Complaint Subject
{title}

## Statement
{body.strip()}

## Owner Certification (to be completed and signed by Albert Lane before submission)
I certify that the above statement is true and accurate to the best of my
knowledge, and that the corroborating material referenced in
OWNER-DECLARATIONS.md is attached or available upon request.

Signature: _____________________
Date: _____________________

---

# ⚠️ DRAFT ONLY — NOT SUBMITTED — OWNER REVIEW REQUIRED ⚠️
"""
    out_path.write_text(content)
    return out_path


def main():
    parser = argparse.ArgumentParser(description="DEI-GTT-001 Intake Pipeline")
    sub = parser.add_subparsers(dest="command", required=True)

    submit = sub.add_parser("submit", help="Process a new submission per Steps 1-9")
    submit.add_argument("--type", required=True, choices=["evidentiary", "terms", "amendment"])
    submit.add_argument("--title", required=True)
    submit.add_argument("--file", required=True, help="Path to a text file with the submission body")
    submit.add_argument("--status", choices=["self-attested", "corroborated"],
                         help="Required for --type evidentiary")
    submit.add_argument("--regulator", choices=list(REGULATOR_TEMPLATES.keys()),
                         help="Only used if --type evidentiary --status corroborated (Step 10)")
    submit.add_argument("--version-bump", choices=["patch", "minor", "major"], default="minor")

    args = parser.parse_args()

    if args.command == "submit":
        body = Path(args.file).read_text()
        version, _ = read_version()

        if args.type == "amendment":
            print("REJECTED (Step 8 / Part X): the Operative Clause (Part II) cannot be")
            print("amended by this script or any automated system. It requires the")
            print("Owner's own direct, verbatim edit. Nothing was filed or changed.")
            return

        if args.type == "terms":
            append_declaration(args.title, body, "Status: Owner's own stated terms — stands as written, no corroboration required.")
            new_version = bump(version, args.version_bump)
            update_taxonomy_version(
                new_version,
                f"Filed Owner's stated terms: \"{args.title}\" via intake_pipeline.py.",
                "Owner submission, Step 2 classification: Statement of Owner's Own Terms.",
            )
            regenerate_manifest(new_version)
            print(f"FILED. Type=terms. Version now {new_version[0]}.{new_version[1]}.{new_version[2]}. "
                  f"No corroboration needed. No regulatory draft applicable.")
            return

        # type == evidentiary
        if not args.status:
            sys.exit("REJECTED: --status is required for --type evidentiary (Step 3).")

        status_line = (
            "Status: SELF-ATTESTED — Owner's own testimony, not independently "
            "corroborated. This is not a finding of falsity (see Part V / Appendix D)."
            if args.status == "self-attested"
            else "Status: CORROBORATED — independent material accompanies this claim."
        )
        append_declaration(args.title, body, status_line)
        new_version = bump(version, args.version_bump)
        update_taxonomy_version(
            new_version,
            f"Filed evidentiary submission \"{args.title}\" at {args.status} status via intake_pipeline.py.",
            "Owner submission, Step 3 evidentiary status assignment.",
        )
        regenerate_manifest(new_version)
        print(f"FILED. Type=evidentiary. Status={args.status}. "
              f"Version now {new_version[0]}.{new_version[1]}.{new_version[2]}.")

        if args.status == "corroborated":
            if not args.regulator:
                print("Status is corroborated but no --regulator given — no draft generated. "
                      "Re-run with --regulator <key> to generate one (Step 10).")
            else:
                path = generate_regulatory_draft(args.title, body, args.regulator)
                if path:
                    print(f"DRAFT GENERATED (not submitted, not sent anywhere): {path}")
        else:
            print("Status is self-attested — no regulatory draft is generated (Step 10 requires Corroborated).")


if __name__ == "__main__":
    main()
